server:
  port: 8080
# 数据库配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://101.201.254.63:3306/oaDB?serverTimezone=GMT%2B8&useAffectedRows=true
      username: oasystem
      password: tangliyi123
      driver-class-name: com.mysql.cj.jdbc.Driver
      web-stat-filter:
        enabled=: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
## mybatis
# sql语句控制台打印执行sql语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

## token jwt
jwt:
  # 密钥
  secret: tangliyi123fddsafasgkahgjdhgkjfhago9gjoasjglkkdsanglkjnfadlkgjnlfkangl;afdngafdng;
  # 过期时间
  expiration: 604800

##swagger
myswagger:
  title: "协同办公系统api接口"

document:
  path: C:\Users\JohnTang\Desktop\oasystem

# 热部署
#spring.devtools.restart.enabled: true

# 生产环节启用
# springfox.documentation.swagger-ui.enabled=false

global-security-config:
  allow-url-list:
    - "/login"
    - "/v2/**"
    - "/swagger-resources/**"
    - "/swagger-resources"
    - "/swagger-ui**"
    - "/webjars/**"